version: 2

workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
  scheduled:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              ignore:
                - gh-pages
    jobs:
      - build

jobs:
  build:
    docker:
      - image: archlinux/archlinux:base
    steps:
      - add_ssh_keys:
          fingerprints:
            - b6:ef:bc:c5:14:21:e5:97:d4:7a:a1:ce:44:78:40:26
      - checkout
      - run:
          command: pacman -Sy && pacman -S --noconfirm --needed glibc bash zsh base-devel git openssh
      - run:
          command: useradd builduser --create-home -g users
      - run:
          command: "echo 'builduser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers"
      - run:
          command: su builduser -c 'git clone https://github.com/rakudo/rakudo.git /tmp/rakudo'
      - run:
          command: cd /tmp/rakudo && su builduser -c 'sudo perl Configure.pl --gen-moar --gen-nqp --backends=moar --prefix=/usr --make-install'
      - run:
          command: cd && rm -rf /tmp/rakudo
      - run:
          command: pacman -S --noconfirm --needed nodejs luajit clang icu nim dotnet-sdk ruby perl perl-json-xs perl-io-all
      - run:
          command: perl run.pl
      - run:
          command: mkdir -p ~/.ssh && ssh-keyscan -H github.com >> ~/.ssh/known_hosts && git config --global user.email "p6-perf@example.com" && git config --global user.name p6-perf
      - run:
          command: git clone git@github.com:Narazaka/p6-perf -b gh-pages html
      - run:
          command: perl summarize.pl && perl archive_summarize.pl html/results
      - run:
          command: cd html && git add . && git commit -m "update result at `perl -MTime::Piece -E 'say gmtime->ymd'`" && git push && cd ..
